export const EXPERIMENT_CARD_WIDTH = 460
export const EXPERIMENT_CARD_COLLAPSED_HEIGHT = 540
export const EXPERIMENT_CARD_EXPANDED_HEIGHT = 880
export const EXPERIMENT_CARD_GAP_X = 136
export const EXPERIMENT_CARD_GAP_Y = 190
